// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snejnwdqgjrajwbpuuoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZWpud2RxZ2pyYWp3YnB1dW9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNDQ3NzQsImV4cCI6MjA2NTYyMDc3NH0.XwqCH75ro1LsJdKi9J2nF19bJTkbY5iN4s4aQLAXVpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);